### ISSUE TITLE
Not really an issue, but do you guys know about subuser?

### ISSUE THREAD

**Issue by timthelion** [subgraph/oz#3]
It seems like your profiles are the same as subuser permissions.json files. Everything feels very similar...

http://subuser.org

**Comment by dma** [comment]
No, we hadn't heard of your project or Kagome until you opened this issue. We've been planning this approach for Subgraph OS for some time and have only recently been able to implement it. Interesting project.

**Comment by timthelion** [comment]
OK, so I'll try to make a quick comarison of subuser and oz:

You have beat me to xpra support. I really want to get that right, and it has taken me some time. Right now, subuser is just doing the entirely insecure: it shares an X11 server with the host. You can see this issue https://github.com/subuser-security/subuser/issues/31 to understand why this is such a hard problem for me.

Where oz has profiles, subuser has [permissions](http://subuser.org/subuser-standard/permissions-dot-json-file-format.html) In this the two projects are *very* similar. Basically, we both store permissions for a given application in a single JSON file.

Subuser makes a very important (in my mind) distinction between applications and use-cases. For example, there is one docker image on my machine which installs firefox, but I have 4 firefox subusers: internet-banking, google-calendar, offline-test-browser, normal-browser. This allows me to confine these use cases to separate containers, as well as give each it's own specific set of permissions. Each of my "firefox" subusers has it's own home directory, and literally does not know that the other versions of firefox exist. I don't know if it is possible in oz to do this yet (it is not clear from my quickly glancing through your readme). Can I install the "evince" profile twice, with sepparate permissions, perhaps for work mail and personal mail?

You may want to have a look at the other similar projects out there, which I have listed here: http://subuser.org/related-projects.html

The one project that is most seriously close to oz/subuser is https://wiki.gnome.org/Projects/SandboxedApps . Gnome's approach to sandboxed apps is similar to that of java web start. If the app wants to do something, like access the webcam, it calls a dbus method, and the user sees a dialog and the user can then confirm or deny the request. I think that the oz/subuser approach to having a single central permissions file is fundamentally superior. It is much more transparent. I also think that constantly prompting the user with security dialogs makes the user feel less secure, which means that the user will be more likely to stop using sandboxed apps and go back to using completely unsecure normal apps :P .

The other thing that I ask myself often, is if with subuser I am not re-inventing Android. Afterall, Android also contains applications and has a central permissions list. The key difference that I see between subuser and Android, is that subuser permissions are much more fine grained and CAN BE EDITED BY THE USER! I think that we can at least learn from Android's mistakes. I think that the "Read/Write SD Card" permission was a major mistake in Android. I know that google wanted to make things simple, but by doing so, they made it so that every app that actually edits files on the system in a sane way has basically full access to everything, which is just plain missing the point of containment.

Regards,

Timothy Hobbs

**Comment by Kagami** [comment]
[sandstorm.io](https://github.com/sandstorm-io/sandstorm) also has [nice permission model](https://github.com/kentonv/etherpad-lite/blob/sandstorm/sandstorm-pkgdef.capnp) driven by the Cap'n Proto.

**Comment by xSmurf** [comment]
Hi @timthelion, thanks for your interest in OZ! I had seen subuser back when I was researching our options but it was not exactly what we were looking for, neither is Sandstorm. OZ is dedicated to transparent desktop interaction. For various reasons we decided to do away with Docker (apart from their golang implementation of netlink, though that is subject to change in the future) or LXC and write a simpler application wrapper for linux namespaces, seccomp, and X isolation and file system sandboxing. As you can see OZ does not require any sort of docker images to be downloaded or otherwise installed and further maintained. As you pointed out, the GNOME sandboxing project is the closest thing, at the time we started working on this they had not released much. But again, it is not exactly what we were looking for as it relies on special "app bundles" that need to be created and maintained separately. It also only works when running from within the gnome environment; start firefox from the CLI and you're screwed. While OZ still allows you to run the applications out of the sandbox, this can be further restricted on the host using something like AppArmor if necessary.

The JSON config files is simply a byproduct of golang, the parser works extremely well and is easy to use. I'll admit it's not my favourite thing to edit by hand but in reality config/profile files rarely need editing so it's not a huge problem worth skipping over the ease of use from the programming side. I intend to write an interactive command for `oz-setup` to help users create new profiles in the future (or maybe even a UI inside the upcoming [OZ gnome shell extension](https://support.subgraph.com/videos/ozshell_evince_01.webm)).

> I don't know if it is possible in oz to do this yet (it is not clear from my quickly glancing through your readme). Can I install the "evince" profile twice, with sepparate permissions, perhaps for work mail and personal mail?

Not at the moment but this is in the works and should be available in the near future.

As for Android, there's definitely some good ideas and lessons to be learned, but we still need full fledged operating systems ([resist the war on general computation!](https://www.youtube.com/watch?v=yYqkU1y0AYc))

@kagami & @timthelion, if you would like to discuss this further you can find me on Freenode (#subgraph) or OFTC. I will be happy to answer any questions you have or help you get it up and running if you want are interested in trying it out.
